name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Run Jest
        run: yarn run test:cov
  e2e-tests:
    name: E2E Tests
    strategy:
      fail-fast: false
      matrix:
        browser: [ 'chromium', 'firefox', 'webkit' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright
        run: npx playwright install --with-deps ${{ matrix.browser }}

      - name: Run Playwright
        run: yarn run test:e2e
